server:
  port: 8087

spring:
  application:
    name: bootcoin-service

  kafka:
    bootstrap-servers: host.docker.internal:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/bootcoin-database

  config:
    import: optional:configserver:http://config-server:8888

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true